app = "check-web"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    VITE_GOOGLE_CLIENT_ID = "958779468996-htmee1pfl9btjab8kag7b1lbo2pd5fq1.apps.googleusercontent.com"

[env]
  NODE_ENV = "production"
  PORT     = "3001"

[http_service]
  internal_port = 3001
  force_https   = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 200
    soft_limit = 150

[[vm]]
  memory   = "512mb"
  cpu_kind = "shared"
  cpus     = 1

[[mounts]]
  source      = "check_game_data"
  destination = "/app/server/data"
